import type { Person, Place } from "./types";

export const STREET_LENGTH = 230;

/** Full street archive lives in the project source; this file is the committed walk data. */
export const places: Place[] = [
  { id: "square", kind: "landmark", meters: 0, depth: 28, side: "axis", year: "2017", name: { en: "Noce i Dnie fountain", pl: "Fontanna Noce i Dnie" }, subtitle: { en: "Where Niecała meets the squares — on the buried arm of the Prosna called Babinka.", pl: "Tu Niecała styka się z placami — nad zasypaną odnogą Prosny zwaną Babinką." }, facade: "/images/fountain-1.jpg", photos: [{ src: "/images/fountain-1.jpg", alt: { en: "Noce i Dnie fountain", pl: "Fontanna Noce i Dnie" }, credit: "Peżot, CC BY-SA 4.0" }, { src: "/images/fountain-2.jpg", alt: { en: "Fountain jets at the square", pl: "Wodotryski na placu" }, credit: "Peżot, CC BY-SA 4.0" }, { src: "/images/fountain-4.jpg", alt: { en: "KANAŁ BABINKA tiles in the pavement", pl: "Płyty KANAŁ BABINKA" }, credit: "Peżot, CC BY-SA 4.0" }, { src: "/images/square-night.jpg", alt: { en: "The square in snow, looking toward Niecała", pl: "Plac zimą, w stronę Niecałej" }, credit: "Aktron, CC BY-SA 4.0" }, { src: "/images/square-jp2.jpg", alt: { en: "John Paul II Square, Kalisz", pl: "Plac św. Jana Pawła II" }, credit: "Peżot, CC BY-SA 4.0" }, { src: "/images/square-kilinski.jpg", alt: { en: "Kiliński Square", pl: "Plac Kilińskiego" }, credit: "Bast, CC BY-SA 3.0" }], story: [{ en: "Niecała begins at the knot of Plac św. Jana Pawła II and Plac Kilińskiego. The fountain here, opened in 2017, sits where Babinka — a side-arm of the Prosna — once ran. Its pale-blue pavement still spells KANAŁ BABINKA. Kalisz named the water for Maria Dąbrowska’s novel Nights and Days, whose world is this city.", pl: "Niecała zaczyna się u zbiegu placu św. Jana Pawła II i placu Kilińskiego. Fontanna z 2017 roku stoi tam, gdzie płynęła Babinka — odnoga Prosny. Na błękitnych płytach wciąż czyta się KANAŁ BABINKA. Miasto nazwało wodę od powieści Marii Dąbrowskiej „Noce i dnie"." }, { en: "A five-domed Orthodox cathedral of Saints Peter and Paul stood on this square from 1877 until it was dismantled after independence. Brick and fittings from that cathedral were reused on Niecała itself, in the small church you will pass on the park side.", pl: "Na tym placu od 1877 roku stał pięciokopułowy sobór Świętych Apostołów Piotra i Pawła, rozebrany po odzyskaniu niepodległości. Cegła i wyposażenie z tamtego soboru wróciły na Niecałą — do małej cerkwi po stronie parku." }], details: [{ label: { en: "Opened", pl: "Uruchomienie" }, value: { en: "October 2017", pl: "październik 2017" } }, { label: { en: "Earlier fountain", pl: "Poprzedniczka" }, value: { en: "Nastroje", pl: "Nastroje" } }, { label: { en: "Named for", pl: "Nazwa" }, value: { en: "Maria Dąbrowska, Nights and Days", pl: "Maria Dąbrowska, Noce i dnie" } }], sources: [{ title: "Kalisz Czasem Malowany — Fontanna Noce i Dnie", url: "https://kaliszczasemmalowany.pl/index.php/2025/fontanna-noce-i-dnie/" }, { title: "Kalisz.pl — Orthodox trail", url: "https://www.kalisz.pl/en/tourists/tourist-routes/on-multicultural-kalisz-trail/orthodox-trail" }] },
  { id: "niecala-2", kind: "building", address: "Niecała 2", meters: 18, depth: 16, side: "north", year: "19th c.", lat: 51.764976, lon: 18.093723, name: { en: "Repphan house", pl: "Dom Repphanów" }, subtitle: { en: "Cloth manufacturers’ house. Stefan Szolc-Rogoziński, explorer of Cameroon, was born here.", pl: "Dom rodziny suchej fabrykanckiej. Tu urodził się Stefan Szolc-Rogoziński, badacz Kamerunu." }, facade: "/images/fountain-1.jpg", photoHonesty: { en: "Commons has no dedicated façade of Niecała 2. The walk uses the western mouth of the street (the fountain) and the family’s nearby cloth mill on Plac Kilińskiego — not this house.", pl: "Na Commons nie ma osobnej elewacji Niecałej 2. Spacer pokazuje zachodnie ujście ulicy (fontannę) i pobliską fabrykę sukna rodziny przy placu Kilińskiego — nie ten dom." }, photos: [{ src: "/images/fountain-1.jpg", alt: { en: "The square at the west end of Niecała, where number 2 stands", pl: "Plac na zachodnim końcu Niecałej, gdzie stoi dwójka" }, credit: "Peżot, CC BY-SA 4.0" }, { src: "/images/repphan-mill.jpg", alt: { en: "Former Beniamin Repphan cloth mill on Plac Kilińskiego — the family works, not the house", pl: "Dawna fabryka sukna Beniamina Repphana przy pl. Kilińskiego — zakład rodziny, nie sam dom" }, credit: "Zala, CC BY-SA 4.0" }, { src: "/images/rogozinski.jpg", alt: { en: "Stefan Szolc-Rogoziński", pl: "Stefan Szolc-Rogoziński" }, credit: "Public domain, NAC" }], story: [{ en: "The Repphans were Protestant cloth manufacturers who helped industrialise Kalisz. On 14 April 1861 Karol Stefan Szolc-Rogoziński was born at Niecała 2.", pl: "Repphanowie byli ewangelickimi sukiennikami. 14 kwietnia 1861 przy Niecałej 2 urodził się Karol Stefan Szolc-Rogoziński." }], details: [{ label: { en: "Born here", pl: "Urodzony tutaj" }, value: { en: "Stefan Szolc-Rogoziński, 1861", pl: "Stefan Szolc-Rogoziński, 1861" } }], people: ["rogozinski", "repphan"], sources: [{ title: "Wikipedia — Stefan Szolc-Rogoziński", url: "https://pl.wikipedia.org/wiki/Stefan_Szolc-Rogozi%C5%84ski" }] },
  { id: "niecala-4", kind: "building", address: "Niecała 4", meters: 38, depth: 22, side: "north", year: "1884 / 1933", lat: 51.764823, lon: 18.093989, name: { en: "Szrajer doll works", pl: "Fabryka lalek Szrajera" }, subtitle: { en: "Peach tenement with iron balconies — one of the Fingerhut–Szrajer factory houses.", pl: "Morelowa kamienica z żeliwnymi balkonami — jeden z domów fabryki Fingerhuta i Szrajera." }, facade: "/images/facade-4.jpg", photos: [{ src: "/images/niecala-4.jpg", alt: { en: "Niecała 4, looking east toward the factory hotel", pl: "Niecała 4, widok na wschód ku hotelowi-fabryce" }, credit: "Michelletto, CC BY-SA 4.0" }, { src: "/images/facade-4.jpg", alt: { en: "Façade of Niecała 4", pl: "Elewacja Niecałej 4" }, credit: "Michelletto, CC BY-SA 4.0" }, { src: "/images/dolls-shirley.jpg", alt: { en: "Shirley-style dolls from the Kalisz factory", pl: "Lalki shirlejki z kaliskiej fabryki" }, credit: "Michelletto, CC BY-SA 4.0" }], story: [{ en: "Jakub Fingerhut opened a doll factory here in 1884. In the 1890s he hired Adam Szrajer, who married his daughter Berta and became director in 1901.", pl: "Jakub Fingerhut otworzył tu fabrykę lalek w 1884. W latach 90. zatrudnił Adama Szrajera, który ożenił się z córką Bertą i w 1901 został dyrektorem." }], details: [{ label: { en: "Founded", pl: "Założenie" }, value: { en: "1884, Jakub Fingerhut", pl: "1884, Jakub Fingerhut" } }], people: ["szrajer", "nestrypke", "kulisiewicz"], sources: [{ title: "Wikipedia — Fabryka Lalek i Zabawek Drewnianych Adama Szrajera", url: "https://pl.wikipedia.org/wiki/Fabryka_Lalek_i_Zabawek_Drewnianych_Adama_Szrajera" }] },
  { id: "niecala-6", kind: "building", address: "Niecała 6 / 6a", meters: 62, depth: 38, side: "north", year: "1884–1965 / 2014", lat: 51.764753, lon: 18.094647, name: { en: "Komoda · the doll factory", pl: "Komoda · dawna fabryka lalek" }, subtitle: { en: "Long modernist slab with a claret ground floor. Today: hotel, restaurant, club.", pl: "Długa modernistyczna bryła z bordowym parterem. Dziś hotel, restauracja i klub." }, facade: "/images/facade-6.jpg", photos: [{ src: "/images/niecala-6.jpg", alt: { en: "Niecała 6, Komoda Residence, looking toward the park", pl: "Niecała 6, Komoda Residence, widok ku parkowi" }, credit: "Michelletto, CC BY-SA 4.0" }, { src: "/images/facade-6.jpg", alt: { en: "Factory hotel façade", pl: "Elewacja hotelu-fabryki" }, credit: "Michelletto, CC BY-SA 4.0" }], story: [{ en: "Number 6 was the working heart of the factory. In 2014 Margota and Cezary Suszyńscy opened Komoda Club Residence here.", pl: "Szóstka była sercem zakładu. W 2014 Margota i Cezary Suszyńscy otworzyli tu Komoda Club Residence." }], details: [{ label: { en: "Now", pl: "Dziś" }, value: { en: "Komoda Residence hotel & restaurant", pl: "Komoda Residence, hotel i restauracja" } }], people: ["szrajer", "suszynscy"], sources: [{ title: "Komoda Residence", url: "https://komodaresidence.pl/" }] },
  { id: "church", kind: "building", address: "Niecała 1", meters: 82, depth: 24, side: "south", year: "1928–1930", lat: 51.76407, lon: 18.094667, name: { en: "Saints Peter and Paul", pl: "Cerkiew św. Piotra i Pawła" }, subtitle: { en: "The small Orthodox church on the park’s northern edge, built from a demolished cathedral.", pl: "Mała cerkiew na północnym skraju parku, wzniesiona z materiału rozebranego soboru." }, facade: "/images/facade-church.jpg", photos: [{ src: "/images/church-front.jpg", alt: { en: "Church from the street, with iron gate", pl: "Cerkiew od ulicy, z kutą furtką" }, credit: "Marek Mróz, CC BY 4.0" }, { src: "/images/church-05.jpg", alt: { en: "Interior and iconostasis", pl: "Wnętrze i ikonostas" }, credit: "Zala, CC BY-SA 4.0" }, { src: "/images/church-2022.jpg", alt: { en: "Church in 2022, parish house behind", pl: "Cerkiew w 2022, za nią dom parafialny" }, credit: "Sławomir Milejski, CC BY-SA 4.0" }], story: [{ en: "Michał Zenowicz designed this neo-Romanesque church; Albert Nestrypke ran the build. Foundation stone 7 April 1929; consecrated 8 January 1930.", pl: "Michał Zenowicz zaprojektował tę neoromańską cerkiew; budową kierował Albert Nestrypke. Kamień węgielny 7 kwietnia 1929; poświęcenie 8 stycznia 1930." }], details: [{ label: { en: "Architect", pl: "Architekt" }, value: { en: "Michał Zenowicz", pl: "Michał Zenowicz" } }], people: ["nestrypke", "zenowicz"], sources: [{ title: "Wikipedia — Cerkiew św. Piotra i Pawła w Kaliszu", url: "https://pl.wikipedia.org/wiki/Cerkiew_%C5%9Awi%C4%99tych_Aposto%C5%82%C3%B3w_Piotra_i_Paw%C5%82a_w_Kaliszu" }] },
  { id: "parish-house", kind: "building", address: "Niecała 1", meters: 94, depth: 14, side: "south", year: "late 19th c.", lat: 51.764522, lon: 18.09442, name: { en: "Orthodox parish house", pl: "Dom Popów" }, subtitle: { en: "The priests’ house of the Orthodox parish, raised at the end of the 19th century beside the later church.", pl: "Dom parafii prawosławnej, wzniesiony pod koniec XIX wieku obok późniejszej cerkwi." }, facade: "/images/parish-yellow.jpg", photos: [{ src: "/images/parish-yellow.jpg", alt: { en: "Parish house beside the church", pl: "Dom parafialny obok cerkwi" }, credit: "Sławomir Milejski, CC BY-SA 4.0" }], story: [{ en: "Kalisz still calls this the Dom Popów — the priests’ house. It predates the 1928–30 church.", pl: "Kaliszanie mówią na ten budynek Dom Popów. Jest starszy od cerkwi z lat 1928–30." }], details: [{ label: { en: "Parish", pl: "Parafia" }, value: { en: "ul. Niecała 1, 62-800 Kalisz", pl: "ul. Niecała 1, 62-800 Kalisz" } }], sources: [{ title: "Fundacja Nasza Historia — Ulica Niecała", url: "https://fundacja-nasza-historia.org.pl/ulica-niecala/" }] },
  { id: "niecala-3", kind: "building", address: "Niecała 3", meters: 108, depth: 14, side: "south", year: "19th–20th c.", lat: 51.764199, lon: 18.094943, name: { en: "Niecała 3", pl: "Niecała 3" }, subtitle: { en: "A house on the park side of the street, mapped in OpenStreetMap between the church and Nestrypke’s villa.", pl: "Dom po stronie parku, zapisany w OpenStreetMap między cerkwią a willą Nestrypkego." }, facade: "/images/church-01.jpg", photoHonesty: { en: "No labelled photograph of Niecała 3 exists on Commons. The walk uses the park-side view immediately east of the church.", pl: "Na Commons nie ma opisanej fotografii Niecałej 3. Spacer używa widoku od parku tuż na wschód od cerkwi." }, photos: [{ src: "/images/church-01.jpg", alt: { en: "Park-side houses beyond the church trees", pl: "Zabudowa od strony parku za drzewami cerkwi" }, credit: "Zala, CC BY-SA 4.0" }], story: [{ en: "Number 3 is part of the continuous front that makes Niecała feel like a street rather than a lane along the park.", pl: "Trójka należy do ciągłej pierzei, dzięki której Niecała jest ulicą, a nie ścieżką wzdłuż parku." }], details: [{ label: { en: "Side", pl: "Strona" }, value: { en: "Park / south", pl: "park / południe" } }], sources: [{ title: "OpenStreetMap — Niecała, Kalisz", url: "https://www.openstreetmap.org/" }] },
  { id: "niecala-8", kind: "building", address: "Niecała 8", meters: 118, depth: 18, side: "north", year: "early 1920s", lat: 51.764741, lon: 18.095117, name: { en: "Szmigielski house", pl: "Dom Szmigielskiego" }, subtitle: { en: "Nestrypke’s early-1920s house for dentist Marcin Szmigielski, with a showy loggia on the street front. Listed in 1995.", pl: "Dom z początku lat 20. dla stomatologa Marcina Szmigielskiego, z efektowną loggią od ulicy. Zabytek od 1995." }, facade: "/images/east-continuation.jpg", photos: [{ src: "/images/east-continuation.jpg", alt: { en: "Looking east along Niecała past the factory toward number 8", pl: "Widok na wschód Niecałą za fabryką, ku ósemce" }, credit: "Michelletto, CC BY-SA 4.0" }], story: [{ en: "The municipal heritage note calls Niecała 8 one of Nestrypke’s successes: a dwelling of the early 1920s whose street wall is opened by a theatrical loggia.", pl: "Miejski opis zabytków nazywa Niecałą 8 jednym z udanych dzieł Nestrypkego: budynek mieszkalny z początku lat 20. z efektowną loggią od ulicy." }], details: [{ label: { en: "Client", pl: "Inwestor" }, value: { en: "Marcin Szmigielski, dentist", pl: "Marcin Szmigielski, stomatolog" } }], people: ["nestrypke"], sources: [{ title: "Calisia.pl — zabytki Niecałej", url: "https://calisia.pl/18-kwietnia-miedzynarodowy-dzien-ochrony-zabytkow-jakie-zabytki-mamy-w-kaliszu,50118" }] },
  { id: "niecala-5", kind: "building", address: "Niecała 5", meters: 134, depth: 16, side: "south", year: "1933–1936", lat: 51.764202, lon: 18.095422, name: { en: "Nestrypke’s villa", pl: "Willa Nestrypkego" }, subtitle: { en: "The modernist house the street’s architect built for himself, on the park’s edge. Listed in 2001.", pl: "Modernistyczna willa, którą architekt ulicy postawił dla siebie na skraju parku. Zabytek od 2001." }, facade: "/images/park-edge-houses.jpg", photos: [{ src: "/images/park-edge-houses.jpg", alt: { en: "Town Park looking toward the Niecała houses", pl: "Park Miejski w stronę domów przy Niecałej" }, credit: "Piotr Zdrowicki, CC BY-SA 3.0" }], story: [{ en: "Albert Nestrypke (1887–1977) was born in Kalisz to Karol, a gardener of this very park. His own house at Niecała 5, 1933–36, still reads as a modernist villa.", pl: "Albert Nestrypke (1887–1977) urodził się w Kaliszu jako syn Karola, ogrodnika właśnie tego parku. Własny dom przy Niecałej 5, z lat 1933–36, wciąż czyta się jako willę modernistyczną." }], details: [{ label: { en: "Built", pl: "Wzniesienie" }, value: { en: "1933–1936", pl: "1933–1936" } }], people: ["nestrypke"], sources: [{ title: "Kalisz.pl — Albert Nestrypke", url: "https://www.kalisz.pl/dla-turysty/zabytki/albert-nestrypke,864" }] },
  { id: "niecala-10", kind: "building", address: "Niecała 10", meters: 150, depth: 20, side: "north", year: "1913", lat: 51.764543, lon: 18.095514, name: { en: "House under the Angels", pl: "Dom Pod Aniołami" }, subtitle: { en: "Evangelical-Augsburg parish house of 1913, with a hostel in the tenement.", pl: "Dom parafialny ewangelików augsburskich z 1913, z hostelem w kamienicy." }, facade: "/images/east-continuation.jpg", photos: [{ src: "/images/east-continuation.jpg", alt: { en: "Niecała continuing east toward the Lutheran house and the park", pl: "Niecała na wschód ku domowi luterańskiemu i parkowi" }, credit: "Michelletto, CC BY-SA 4.0" }], story: [{ en: "In 1913 the Lutheran parish built a new house on Niecała and moved its elementary school here. Today the parish office is still at Niecała 10.", pl: "W 1913 parafia luterańska postawiła nowy dom przy Niecałej i przeniosła tu szkołę elementarną. Kancelaria parafii nadal jest przy Niecałej 10." }], details: [{ label: { en: "Built", pl: "Wzniesienie" }, value: { en: "1913", pl: "1913" } }], people: ["wende"], sources: [{ title: "Parafia Ewangelicko-Augsburska w Kaliszu", url: "https://kalisz.luteranie.pl/" }] },
  { id: "niecala-12", kind: "building", address: "Niecała 12", meters: 168, depth: 14, side: "north", year: "1891", lat: 51.764503, lon: 18.095837, name: { en: "Boretti studio", pl: "Atelier Borettiego" }, subtitle: { en: "Warsaw Photographic Studio of Wincenty Boretti, licensed 29 May 1891 — the street’s camera.", pl: "Warszawski Zakład Fotograficzny Wincentego Borettiego, koncesja 29 maja 1891 — aparat tej ulicy." }, facade: "/images/boretti-portrait.jpg", photos: [{ src: "/images/boretti-portrait.jpg", alt: { en: "Portrait of a woman of Kalisz by Wincenty Boretti", pl: "Portret kaliszanki Wincentego Borettiego" }, credit: "Wincenty Boretti / Wikimedia, CC BY-SA 4.0" }], story: [{ en: "Wincenty Franciszek Boretti opened here, at number 12, the Warszawski Zakład Fotograficzny in 1891.", pl: "Wincenty Franciszek Boretti otworzył tutaj, pod dwunastką, Warszawski Zakład Fotograficzny w 1891." }], details: [{ label: { en: "Studio from", pl: "Zakład od" }, value: { en: "29 May 1891", pl: "29 maja 1891" } }], people: ["boretti"], sources: [{ title: "Calisia.pl — Wincenty Franciszek Boretti", url: "https://calisia.pl/prekursor-kaliskich-fotografikow-wincenty-franciszek-boretti-1859-1932,27214" }] },
  { id: "niecala-14", kind: "building", address: "Niecała 14", meters: 186, depth: 18, side: "south", year: "1920", lat: 51.764176, lon: 18.096102, name: { en: "Boretti house", pl: "Dom Borettiego" }, subtitle: { en: "Classicising tenement of 1920 at the park gate — the photographer’s family palace.", pl: "Klasycyzująca kamienica z 1920 tuż przy wejściu do parku — rodzinny pałac fotografa." }, facade: "/images/park-path-white.jpg", photos: [{ src: "/images/park-edge-houses.jpg", alt: { en: "Park allée toward the white house on Niecała", pl: "Aleja parku ku białemu domowi przy Niecałej" }, credit: "Piotr Zdrowicki, CC BY-SA 3.0" }], story: [{ en: "The 1920 classicising tenement at number 14 stands at the park entrance. Boretti died in Radom in 1932.", pl: "Klasycyzująca kamienica z 1920 pod czternastką stoi przy wejściu do parku. Boretti zmarł w Radomiu w 1932." }], details: [{ label: { en: "Built", pl: "Wzniesienie" }, value: { en: "1920", pl: "1920" } }], people: ["boretti"], sources: [{ title: "Fotopolska — ul. Niecała", url: "https://fotopolska.eu/Kalisz/u58269,ul_Niecala.html" }] },
  { id: "niecala-7", kind: "building", address: "Niecała 7", meters: 208, depth: 14, side: "south", year: "1905–1910", lat: 51.763743, lon: 18.09611, name: { en: "Park keeper’s cottage", pl: "Domek Parkowego" }, subtitle: { en: "The last surviving park-keeper’s house, listed with the park.", pl: "Ostatni ocalały domek opiekuna parku, wpisany wraz z parkiem." }, facade: "/images/park-spring.jpg", photos: [{ src: "/images/park-spring.jpg", alt: { en: "Spring in the Town Park", pl: "Wiosna w Parku Miejskim" }, credit: "Piotr Zdrowicki, CC BY-SA 3.0" }], story: [{ en: "Kalisz’s Town Park, 1798, is the oldest public park in Poland. This cottage, 1905–10, is the one that remains.", pl: "Park Miejski z 1798 to najstarszy park publiczny w Polsce. Ten domek z lat 1905–10 ocalał." }], details: [{ label: { en: "Date", pl: "Data" }, value: { en: "1905–1910", pl: "1905–1910" } }], sources: [{ title: "Kalisz Czasem Malowany — Domek Parkowego", url: "https://kaliszczasemmalowany.pl/index.php/2025/domek-parkowego-w-parku-miejskim/" }] },
  { id: "park", kind: "park", meters: 230, depth: 40, side: "axis", year: "1798", lat: 51.76, lon: 18.095278, name: { en: "Town Park", pl: "Park Miejski" }, subtitle: { en: "The oldest municipal park in Poland. Niecała was first a short curve along its edge — hence the name: not-quite-a-street.", pl: "Najstarszy park miejski w Polsce. Niecała była najpierw krótkim łukiem wzdłuż jego skraju — stąd nazwa: ulica niecała." }, facade: "/images/park-1.jpg", photos: [{ src: "/images/park-1.jpg", alt: { en: "Town Park lawns", pl: "Trawniki Parku Miejskiego" }, credit: "LukaszKalisz, CC BY-SA 3.0" }, { src: "/images/park-2.jpg", alt: { en: "Park paths", pl: "Aleje parku" }, credit: "Tezlubiezabytki, CC BY-SA 3.0" }, { src: "/images/tyniec-bridge.jpg", alt: { en: "Tyniec Bridge at the east end", pl: "Most Tyniecki na wschodnim końcu" }, credit: "Piotr Zdrowicki, CC BY-SA 3.0" }], story: [{ en: "President Jan Karol Horning laid the park out in 1798 on former Jesuit vegetable gardens. It is 24 hectares, listed in 1964.", pl: "Prezydent Jan Karol Horning założył park w 1798 na pojezuickich ogrodach warzywnych. 24 hektary, wpis 1964." }], details: [{ label: { en: "Founded", pl: "Założenie" }, value: { en: "1798", pl: "1798" } }, { label: { en: "Area", pl: "Powierzchnia" }, value: { en: "24.28 ha", pl: "24,28 ha" } }, { label: { en: "Street length", pl: "Długość ulicy" }, value: { en: "just over 230 m", pl: "nieco ponad 230 m" } }], sources: [{ title: "Wikipedia — Park Miejski w Kaliszu", url: "https://pl.wikipedia.org/wiki/Park_Miejski_w_Kaliszu" }] },
];

export const people: Person[] = [
  { id: "rogozinski", name: "Stefan Szolc-Rogoziński", years: "1861–1896", photo: "/images/rogozinski.jpg", placeIds: ["niecala-2"], bio: { en: "Born at Niecała 2. Naval officer, Fellow of the Royal Geographical Society, leader of the first Polish research expedition to Africa.", pl: "Urodzony przy Niecałej 2. Oficer marynarki, członek Królewskiego Towarzystwa Geograficznego, kierownik pierwszej polskiej wyprawy badawczej do Afryki." } },
  { id: "szrajer", name: "Adam Szrajer", years: "1873–1934", placeIds: ["niecala-4", "niecala-6"], bio: { en: "Doll manufacturer, son-in-law of Jakub Fingerhut. Celluloid pioneer, gold medal at Poznań 1929.", pl: "Fabrykant lalek, zięć Jakuba Fingerhuta. Pionier celluloidu, złoty medal PeWuKi 1929." } },
  { id: "kulisiewicz", name: "Tadeusz Kulisiewicz", years: "1899–1988", photo: "/images/kulisiewicz.jpg", placeIds: ["niecala-4"], bio: { en: "Graphic artist, born in Kalisz. His father Walenty kept a locksmith’s shop at Niecała 4.", pl: "Grafik, urodzony w Kaliszu. Ojciec Walenty miał warsztat ślusarski przy Niecałej 4." } },
  { id: "boretti", name: "Wincenty Franciszek Boretti", years: "1859–1932", photo: "/images/boretti-portrait.jpg", placeIds: ["niecala-12", "niecala-14"], bio: { en: "First great photographer of Kalisz. Studio at Niecała 12 from 1891, classicising house at 14 from 1920.", pl: "Pierwszy wielki fotograf Kalisza. Zakład przy Niecałej 12 od 1891, klasycyzujący dom pod 14 z 1920." } },
  { id: "nestrypke", name: "Albert Nestrypke", years: "1887–1977", placeIds: ["niecala-5", "niecala-8", "niecala-4", "church"], bio: { en: "County architect, son of the park gardener. Karlsruhe-trained modernist. His villa is at number 5.", pl: "Architekt powiatowy, syn ogrodnika parkowego. Modernista z Karlsruhe. Willa pod piątką." } },
  { id: "zenowicz", name: "Michał Zenowicz", years: "fl. 1928", placeIds: ["church"], bio: { en: "Architect of the neo-Romanesque Orthodox church.", pl: "Architekt neoromańskiej cerkwi." } },
  { id: "wende", name: "Edward Wende", years: "pastor from 1906", placeIds: ["niecala-10"], bio: { en: "Lutheran pastor who multiplied Polish-language services and saw the 1913 parish house rise on Niecała.", pl: "Pastor luterański, który mnożył nabożeństwa po polsku i doczekał domu parafialnego przy Niecałej w 1913." } },
  { id: "repphan", name: "Repphan family", years: "18th–19th c.", placeIds: ["niecala-2"], bio: { en: "Protestant cloth manufacturers. Beniamin’s daughter Fryderyka married Karol Scholtz; their grandson was Szolc-Rogoziński.", pl: "Ewangeliccy sukiennicy. Córka Beniamina, Fryderyka, wyszła za Karola Scholtza; ich wnukiem był Szolc-Rogoziński." } },
  { id: "suszynscy", name: "Margota & Cezary Suszyńscy", years: "2010s–", placeIds: ["niecala-6"], bio: { en: "Owners of Komoda. They turned the doll factory into a hotel and club, founded the Street Festival of Niecała.", pl: "Właściciele Komody. Z fabryki lalek zrobili hotel i klub, wymyślili Święto Ulicy Niecałej." } },
];

export const festival = {
  title: { en: "Święto Ulicy Niecałej", pl: "Święto Ulicy Niecałej" },
  story: {
    en: "Each year at the start of September the 230 metres fill with Szrajer dolls, vintage cars, a hurdy-gurdy, samovar tea, chess, theatre costumes and a flea market. The festival has run since 2013; the 14th edition was 5 September 2026.",
    pl: "Na początku września, od 2013 roku, 230 metrów wypełniają lalki Szrajera, zabytkowe auta, katarynka, herbata z samowara, szachy, kostiumy i pchli targ. XIV edycja: 5 września 2026.",
  },
  sources: [
    { title: "Radio Poznań — 220 metrów historii", url: "https://radiopoznan.fm/informacje/pozostale/220-metrow-historii-dzis-swieto-ulicy-niecalej-w-kaliszu" },
    { title: "Kalisz Czasem Malowany — Święto 2023", url: "https://kaliszczasemmalowany.pl/index.php/2023/niecala-swieto-ulicy-2023/" },
  ],
};

export const nameHistory = [
  { year: "mid-19th c.", en: "Laid out; named Niecała because it was a short curve from the Bernardynka along the park.", pl: "Wytyczona; nazwana Niecałą, bo była krótkim łukiem od Bernardynki wzdłuż parku." },
  { year: "1906", en: "Present line after the city limits expand.", pl: "Obecny przebieg po powiększeniu miasta." },
  { year: "1934", en: "Bronisław Pieracki Street.", pl: "Ulica Bronisława Pierackiego." },
  { year: "1946", en: "Walki Młodych Street.", pl: "Ulica Walki Młodych." },
  { year: "1990", en: "Niecała restored.", pl: "Przywrócono nazwę Niecała." },
];
